// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.15.8
// source: data_message.proto

package go_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataMessageType int32

const (
	DataMessageType_BOT  DataMessageType = 0
	DataMessageType_USER DataMessageType = 1
)

// Enum value maps for DataMessageType.
var (
	DataMessageType_name = map[int32]string{
		0: "BOT",
		1: "USER",
	}
	DataMessageType_value = map[string]int32{
		"BOT":  0,
		"USER": 1,
	}
)

func (x DataMessageType) Enum() *DataMessageType {
	p := new(DataMessageType)
	*p = x
	return p
}

func (x DataMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_data_message_proto_enumTypes[0].Descriptor()
}

func (DataMessageType) Type() protoreflect.EnumType {
	return &file_data_message_proto_enumTypes[0]
}

func (x DataMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataMessageType.Descriptor instead.
func (DataMessageType) EnumDescriptor() ([]byte, []int) {
	return file_data_message_proto_rawDescGZIP(), []int{0}
}

type DataMessageBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DataMessageBody) Reset() {
	*x = DataMessageBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataMessageBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMessageBody) ProtoMessage() {}

func (x *DataMessageBody) ProtoReflect() protoreflect.Message {
	mi := &file_data_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMessageBody.ProtoReflect.Descriptor instead.
func (*DataMessageBody) Descriptor() ([]byte, []int) {
	return file_data_message_proto_rawDescGZIP(), []int{0}
}

type DataMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      DataMessageType  `protobuf:"varint,1,opt,name=type,proto3,enum=go_protocol.DataMessageType" json:"type,omitempty"`
	MessageId *string          `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3,oneof" json:"message_id,omitempty"`
	RoomId    string           `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomSid   string           `protobuf:"bytes,4,opt,name=room_sid,json=roomSid,proto3" json:"room_sid,omitempty"`
	To        string           `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	Body      *DataMessageBody `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *DataMessage) Reset() {
	*x = DataMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMessage) ProtoMessage() {}

func (x *DataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_data_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMessage.ProtoReflect.Descriptor instead.
func (*DataMessage) Descriptor() ([]byte, []int) {
	return file_data_message_proto_rawDescGZIP(), []int{1}
}

func (x *DataMessage) GetType() DataMessageType {
	if x != nil {
		return x.Type
	}
	return DataMessageType_BOT
}

func (x *DataMessage) GetMessageId() string {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return ""
}

func (x *DataMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *DataMessage) GetRoomSid() string {
	if x != nil {
		return x.RoomSid
	}
	return ""
}

func (x *DataMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *DataMessage) GetBody() *DataMessageBody {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_data_message_proto protoreflect.FileDescriptor

var file_data_message_proto_rawDesc = []byte{
	0x0a, 0x12, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x42, 0x6f, 0x64, 0x79, 0x22, 0xe8, 0x01, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x53, 0x69, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x30,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67,
	0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x2a,
	0x24, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x4f, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x55,
	0x53, 0x45, 0x52, 0x10, 0x01, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x61, 0x6c, 0x6c, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x73, 0x6d, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_message_proto_rawDescOnce sync.Once
	file_data_message_proto_rawDescData = file_data_message_proto_rawDesc
)

func file_data_message_proto_rawDescGZIP() []byte {
	file_data_message_proto_rawDescOnce.Do(func() {
		file_data_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_message_proto_rawDescData)
	})
	return file_data_message_proto_rawDescData
}

var file_data_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_data_message_proto_goTypes = []interface{}{
	(DataMessageType)(0),    // 0: go_protocol.DataMessageType
	(*DataMessageBody)(nil), // 1: go_protocol.DataMessageBody
	(*DataMessage)(nil),     // 2: go_protocol.DataMessage
}
var file_data_message_proto_depIdxs = []int32{
	0, // 0: go_protocol.DataMessage.type:type_name -> go_protocol.DataMessageType
	1, // 1: go_protocol.DataMessage.body:type_name -> go_protocol.DataMessageBody
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_data_message_proto_init() }
func file_data_message_proto_init() {
	if File_data_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataMessageBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_data_message_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_message_proto_goTypes,
		DependencyIndexes: file_data_message_proto_depIdxs,
		EnumInfos:         file_data_message_proto_enumTypes,
		MessageInfos:      file_data_message_proto_msgTypes,
	}.Build()
	File_data_message_proto = out.File
	file_data_message_proto_rawDesc = nil
	file_data_message_proto_goTypes = nil
	file_data_message_proto_depIdxs = nil
}
